name = "L Pack"
author = "Ehllie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d132e4c4de8e3d1b5a6dbe22b18af2ba940177e8501512eb869bd118e57fdfb7"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"
