name = "L Craft"
author = "Ehllie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a48f303584d38860a2ff03b0a31f9dbaec19fe8aace65244c4dbf19a46945515"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1"]
